[app]
name = "goal"
key = "dQcxsKvBZKNfWivwnhKlDwvseguknBZPEiiDRQlIatjKLLpbzK"
env = "local"
debug = true

[http]
host = "0.0.0.0"
port = "8008"


[queue]
connection = "nsq"
kafka.brokers = "localhost:9092"
nsq.address = "localhost:49156"

[db]
connection = "mysql"
host = "localhost"
port = "3306"
database = "goal"
username = "root"
password = 123456

[db.sqlite]
database = "/Users/qbhy/Downloads/goal-web/goal/database/database.sqlite"

[db.pgsql]
host = "localhost"
port = "55433"
database = "postgres"
username = "postgres"
password = "123456"

[redis]
host = "hsy"
port = "6379"
password="123456"

[redis.cache]
host = "hsy"
port = "6379"
db = 1

# 缓存配置
[cache]
driver = "redis"
connection = "cache"
prefix = "redis_"

# 哈希配置
[hashing]
driver = "bcrypt"
cost = "14"
salt = "goal"
# 自定义哈希
[hashing.hashers]
md5.driver = "md5"
md5.salt = "goal"

# 文件系统配置
[filesystem]
driver = "local"
root = "/Users/qbhy/project/go/goal/"
perm = "0777"

[filesystem.qiniu]
private = "false"
bucket = "aa"
domain = "https://xxx.xxx.com"
access_key = ""
secret_key = ""

# session 配置
[session]
id = "goal"
name = "goal_session:"

